name: mauri

services:
  server:
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    ports:
      - "3100:3000"
    environment:
      NODE_PORT: 3000
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER}:${PG_DATABASE_PASSWORD}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/${PG_DATABASE_NAME:-default}

      SERVER_URL: ${SERVER_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}

      APP_SECRET: ${APP_SECRET}

      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      DISABLE_DB_MIGRATIONS: "false"
      DISABLE_CRON_JOBS_REGISTRATION: "false"

      SIGN_IN_PREFILLED: "false"
      IS_WORKSPACE_CREATION_LIMITED_TO_SERVER_ADMINS: "true"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/healthz"]
      interval: 5s
      timeout: 5s
      retries: 20

    restart: always

  worker:
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - server-local-data:/app/packages/twenty-server/.local-storage
    command: ["yarn", "worker:prod"]

    environment:
      PG_DATABASE_URL: postgres://${PG_DATABASE_USER}:${PG_DATABASE_PASSWORD}@${PG_DATABASE_HOST:-db}:${PG_DATABASE_PORT:-5432}/${PG_DATABASE_NAME:-default}

      SERVER_URL: ${SERVER_URL}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}

      APP_SECRET: ${APP_SECRET}

      STORAGE_TYPE: ${STORAGE_TYPE:-local}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_NAME: ${STORAGE_S3_NAME}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      DISABLE_DB_MIGRATIONS: "true"
      DISABLE_CRON_JOBS_REGISTRATION: "true"

    depends_on:
      db:
        condition: service_healthy
      server:
        condition: service_healthy

    restart: always

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME:-default}
      POSTGRES_USER: ${PG_DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_DATABASE_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_DATABASE_USER:-postgres} -h localhost -d ${PG_DATABASE_NAME:-default}"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: always

  redis:
    image: redis
    command: ["--maxmemory-policy", "noeviction"]

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: always

volumes:
  db-data:
  server-local-data:
